DWAPlannerROS:
  acc_lim_x: 1.7
  acc_lim_y: 1.7
  acc_lim_th: 1.7

  max_trans_vel: 1.5
  min_trans_vel: 0.1
  
  max_vel_x: 1.0
  min_vel_x: -1.0
  max_vel_theta: 1.2
  min_vel_theta: 0.1

  max_vel_y: 1.0
  min_vel_y: -1.0

  max_rot_vel: 1.0
  min_rot_vel: 0.3

  holonomic_robot: true

  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

  sim_time: 1.7
  sim_granularity: 0.025
  vx_samples: 8
  vy_samples: 5
  vtheta_samples: 20
  penalize_negative_x: true

  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.05
  forward_point_distance: 0.325
  stop_time_buffer: 0.5
  scaling_speed: 0.1
  max_scaling_factor: 0.5
