obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.7,0.38], [0.7,-0.38], [-0.7,-0.38], [-0.7,0.38]]
obstacles:
    observation_sources: base_scan water
    base_scan: {sensor_frame: laser, data_type: LaserScan, topic: /scan_filtered, marking: true, clearing: true}
    water: {data_type: PointCloud, topic: /waterPointCloud, marking: true}
inflation:
    inflation_radius: 0.1
    cost_scaling_factor: 10.0 

