obstacle_range: 4.5
raytrace_range: 5.0
footprint: [[0.29,0.19], [0.29,-0.19], [-0.29,-0.19], [-0.29,0.19]]
#robot_radius: 0.5
inflation_radius: 0.1

observation_sources: laser_scan_sensor water_cloud

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan_filtered, marking: true, clearing: true}
water_cloud: {data_type: PointCloud, topic: /waterPointCloud, marking: true}
