global_costmap:
  global_frame: /map
  robot_base_frame: base_link_turned
  update_frequency: 5.0
  publish_frequency: 2.0
  resolution: 0.05
  static_map: true
  plugins: 
    - {name: static_map,       type: "costmap_2d::StaticLayer"}
    - {name: obstacles,        type: "costmap_2d::VoxelLayer"}
    - {name: inflation,        type: "costmap_2d::InflationLayer"}
