local_costmap:
  global_frame: odom
  robot_base_frame: base_link_turned
  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 100.0
  height: 100.0
  resolution: 0.05
  origin_x: 0.0
  origin_y: 0.0
  plugins: 
    - {name: obstacles,        type: "costmap_2d::VoxelLayer"}
    - {name: inflation,        type: "costmap_2d::InflationLayer"}
