obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.290,0.190], [0.290,-0.190], [-0.290,-0.190], [-0.290,0.190]]
obstacles:
    observation_sources: base_scan water
    base_scan: {sensor_frame: base_laser_back_link, data_type: LaserScan, topic: /scan_back, marking: true, clearing: true}
    water: {data_type: PointCloud, topic: /waterPointCloud, marking: true}
inflation:
    inflation_radius: 0.25
    cost_scaling_factor: 15.0   

