obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.35,0.19], [0.35,-0.19], [-0.35,-0.19], [-0.35,0.19]]
#robot_radius: 0.5
inflation_radius: 0.1

observation_sources: laser_scan_sensor water_cloud

laser_scan_sensor: {sensor_frame: base_laser_back_link, data_type: LaserScan, topic: /scan_back, marking: true, clearing: true}
water_cloud: {data_type: PointCloud, topic: /waterPointCloud, marking: true}
